language: python
python:
  - "3.5"
cache: pip
install:
  - echo "Installing dependencies!"
  - pip install -r requirements.txt
  - strace -f -r bash -c 'export MOOD="happy"'
  - echo $MOOD
script:
  - python -m unittest discover -v
